### ISSUE TITLE
Alias Path for Components

### ISSUE THREAD

**Issue by ghost** [NPeredoEsquivel/pomodoro_app#19]
Implementar alias `@path` para evitar este tipo de imports `../../../../store/slices/tasksSlice`.

Para transformar esos imports en algo como lo siguiente:
- `import { Button } from @components/button`
- `import { tasksSlice } from @store/slices`

Lo anterior, implica también reemplazar los `export default` por `export` en donde sea posible.

Resources:
- https://dev.to/tilly/aliasing-in-vite-w-typescript-1lfo
- https://medium.com/@danil_chepelev/how-to-setup-path-aliases-with-react-typescript-and-webpack-54e579c189e1

**Comment by NPeredoEsquivel** [comment]
Como ahora uso Vite, creo que esto me puede servir. Lo dejo acá como reminder: https://dev.to/tilly/aliasing-in-vite-w-typescript-1lfo

**Comment by NPeredoEsquivel** [comment]
https://github.com/NPeredoEsquivel/pomodoro_app/pull/27
